version: '3'
services:
  nginx:
    restart: 'no'
    build:
      context: ./nginx
    volumes:
      - ./nginx/dev/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/lua/:/home/ubuntu/ngx_lua_anticc/
      - ./log/:/var/log/nginx/
      - ./nginx/html/:/usr/local/openresty/nginx/html/
    network_mode: "host"
