version: '3'
services:
  haproxy_lb:
    build: ./haproxy
    volumes:
      - ./haproxy:/etc/haproxy/
      #- /var/run/docker.sock:/tmp/docker.sock
    #ports:
    #  - 80:80
    #  - 443:443
    network_mode: host
