kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/andrey"