kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-for-master-redis-0
  namespace: dev-redis
spec:
  storageClassName: "openebs-device"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi